title: Yechiels CV
description:  my CV.
url: sulzy3.github.io
   baseurl: /jekyll-cv-main
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
