title: Lejbs CV
description:  my CV.
baseurl: /my-cv
url: https://gologolo24.github.io 
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
